require "user.reload"
require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.copilot"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.lualine"
require "user.indentline"
require "user.mason"
require "user.lsp"
require "user.null-ls"

require "user.colorizer"
